"""empty message

Revision ID: 10d289442734
Revises: 932b1df6a5a5
Create Date: 2024-07-28 20:11:23.772286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d289442734'
down_revision: Union[str, None] = '932b1df6a5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('annotations', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('annotations_user_id_message_id', table_name='annotations')
    op.create_index('annotations_conversation_id', 'annotations', ['conversation_id'], unique=False)
    op.create_index('annotations_user_message_id', 'annotations', ['user_id', 'message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('annotations_user_message_id', table_name='annotations')
    op.drop_index('annotations_conversation_id', table_name='annotations')
    op.create_index('annotations_user_id_message_id', 'annotations', ['user_id', 'message_id'], unique=False)
    op.alter_column('annotations', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('annotations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
