"""empty message

Revision ID: 932b1df6a5a5
Revises: ed17f144f4bf
Create Date: 2024-07-25 01:32:42.455846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932b1df6a5a5'
down_revision: Union[str, None] = 'ed17f144f4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('htext', sa.String(), nullable=False),
    sa.Column('annotation', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('annotations_conversation_id_message_id', 'annotations', ['conversation_id', 'message_id'], unique=False)
    op.create_index('annotations_user_id_message_id', 'annotations', ['user_id', 'message_id'], unique=False)
    op.create_index('annotations_message_id', 'annotations', ['message_id'], unique=False)
    op.create_index('annotations_user_id', 'annotations', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('is_annotation_response', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_annotation_response')
    op.drop_index('annotations_user_id', table_name='annotations')
    op.drop_index('annotations_message_id', table_name='annotations')
    op.drop_index('annotations_conversation_id_message_id', table_name='annotations')
    op.drop_index('annotations_conversation_id', table_name='annotations')
    op.drop_table('annotations')
    # ### end Alembic commands ###
