'use client';

import React, { useEffect, useState } from 'react';
import { Markdown } from '@/components/Shared';
import { hasAcceptedUserAgreement, acceptUserAgreement } from '@/pages_old/cookies';
import { setLocalStorage, setCookie } from '@/pages_old/cookies';
import { v4 as uuidv4 } from 'uuid';
import { useCohereClient } from '@/cohere-client';

interface UserAgreementModalProps {
  onAccept?: () => void;
}

export const TermsModal: React.FC<{ onAccept: () => void }> = ({ onAccept }) => {
  const [showTerms, setShowTerms] = useState(false);

  useEffect(() => {
    const hasAccepted = hasAcceptedUserAgreement();
    if (!hasAccepted) {
      setShowTerms(true);
    }
  }, []);

  const client = useCohereClient();

  // window.confirm('By clicking OK, I confirm that I am 18+ and agree that my data may be published or shared.'

  const handleAcceptClick = () => {
    if (true) {
      onAccept();
      acceptUserAgreement();
        client.createUser({
          email: "null",
          fullname: "null",
          headers: client.getHeaders()
        }).catch(error => {
          console.error('Failed to create user:', error);
        });
    }
  };

  if (!showTerms) return null;

  return (
    <div className="modal bg-marble-100">
      <div className="modal-content rounded-lg border border-marble-400">
        <span className="modal-title" style={{ fontFamily: 'Cambria', fontSize: '25px', fontWeight: 'bold' }}>
          Chat Annotator User Agreement
        </span>
        <hr style={{ paddingTop: '0.5rem', paddingBottom: '0.2rem'}}/>
        <div className="modal-body scrollable">
              <Markdown 
                style={{ fontSize: '15px' }} 
                // text={`By using our app, which is powered by Cohere's API, you acknowledge and agree to the following terms regarding the data you provide:\n\n\u200B\n\n1. **Eligibility:** You must be **at least 18 years old** to use this app. By continuing to use the app, you confirm that you meet this age requirement.\n\n2. **Collection:** We may collect information, including the inputs you type into our app, the outputs generated by Cohere's API, and certain technical details about your device and connection (such as browser type, operating system, and IP address) provided by your device's request headers.\n\n3. **Use:** We may use the collected data for research purposes, to improve our services, and to develop new products or services, including commercial applications, and for security purposes, such as protecting against unauthorized access and attacks.\n\n4. **Sharing and Publication:** Your data, including the technical details collected from your device's request headers, may be published, shared with third parties, or used for analysis and reporting purposes.\n\n5. **Data Retention:** We may retain your data, including the technical details collected from your device's request headers, for as long as necessary.\n\n\u200B\n\nBy continuing to use our app, you provide your **explicit consent** to the collection, use, and potential sharing of your data as described above. If you **do not agree** with our data collection, use, and sharing practices, or if you **are under 18 years old**, please **do not use our app**.`}
                // text={'By providing your consent, you are not waiving your legal rights or releasing the investigator(s) or involved institution(s) from their legal and professional responsibilities. By using our app you agree to the following:\n\n\u200B\n\n1. **I agree** to participate in this study.\n\n2. **I agree** that my anonymized data (including chatbot prompts, responses, annotations, device metadata, approximate geographic location, and hashed IP address) can be used in any papers, presentations, or publications that result from this research.\n\n3. **I agree** that my anonymized data (including chatbot prompts, responses, annotations, device metadata, approximate geographic location, and hashed IP address) can be shared in a public online repository (e.g., Hugging Face), as described in the [information letter](https://chatannotator.com/information_letter.pdf).\n\n 4. **I agree** to allowing my study data to be used for future purposes as described in the [information letter](https://chatannotator.com/information_letter.pdf).\n\n\u200B\n\n By selecting accept below and using our app, you agree to these terms. If you do not agree with our data collection and sharing practices, please do not use our app.'}
                text={`**Study Title:** Crowdsourcing Fine-Grained Chatbot Feedback: Collecting Real-World Conversations and Annotations

**Faculty Supervisor:** Yuntian Deng, PhD, School of Computer Science, University of Waterloo. 

**Email:** yuntian@uwaterloo.ca

\u200B

This letter explains what the study is about, possible risks and benefits, and your rights as a research participant. You may print/save a copy for your records. If you do not understand something in the letter, please ask one of the investigators before consenting to participate.

\u200B

**What is the study about?**
You are invited to participate in a research study exploring how people interact with AI chatbots and provide feedback on their responses. The goal of this study is to collect fine-grained user annotations (e.g., identifying specific errors or issues in chatbot outputs) to better understand where large language models (LLMs) make mistakes and how to improve them. Your interactions will help build an open- source dataset for use by the research community.

**What does participation involve?**
Participation involves chatting with a web-based AI chatbot at https://chatannotator.com. You can type questions or prompts to the chatbot and receive generated responses.
You will have the optional ability to:
*   Highlight specific parts of a chatbot's response
*   Provide annotations or feedback (e.g., correcting mistakes or clarifying issues)

**Who may participate in the study?**
To participate in the study, you need to be at least 18 years of age.

**Is participation in the study voluntary?**
Your participation in this study is voluntary.

**Will I receive anything for participating in the study?**
You will not receive any renumeration for participating in this study.

**What are the possible benefits of the study?**
While there is no direct personal benefit to you, your participation will contribute to the development of more accurate and reliable AI chatbot systems. The resulting dataset will be publicly released to support open research in natural language processing.

**What are the risks associated with the study?**
There are no known or anticipated risks associated with participation. However, as with any online interaction, there is a minimal risk of unintentional disclosure of information through your inputs. We encourage you not to include any personal or sensitive information in your prompts.

**How is data collected, stored, and protected?**
The following data will be collected:
*   Chatbot interactions: The prompts you enter and the chatbot's responses
*   Annotations: Feedback you provide, including highlighted text spans and comments
*   Technical metadata: Your device type (mobile/desktop), browser type, and your approximate location (at the state or province level), inferred from your IP address
*   Hashed IP address: This allows us to link multiple sessions from the same user while maintaining privacy. IPs are hashed using a secure, non-reversible function such that your real IP address cannot be reconstructed from hashed IP addresses.

To ensure privacy:
*   We will periodically run automated tools to detect and remove personally identifiable information (PII) from the data.
*   A final PII removal will occur before any public release of the dataset (e.g., on Hugging Face). All data will be securely stored on password-protected servers during the research phase.

After data cleaning and anonymization, the dataset will be publicly released on Hugging Face, a platform widely used by the machine learning and natural language processing research community. Other researchers will be able to access and use this dataset for other research purposes.

**Who is sponsoring/funding this study?**
This study is funded by a Canadian NSERC Discovery grant.

**Has the study received ethics clearance?**
This study has been reviewed and received ethics clearance through a University of Waterloo Research Ethics Board (REB 47306). If you have questions for the Board, contact the Office of Research Ethics, toll- free at 1-833-643-2379 (Canada and USA), 1-519-888-4440, or reb@uwaterloo.ca.

**Who should I contact if I have questions regarding my participation in the study?**
If you have any questions about this study or need more information before you decide whether to participate, please contact one of the researchers named above.

\u200B

**Collection Practices Consent**

- I am aware that the data I provide (including chatbot prompts, responses, annotations, device metadata, approximate geographic location, and hashed IP address) may be shared as part of an anonymized public dataset, as described in the information letter. I am aware that this dataset may also be accessed and used by other researchers in the broader research community for research purposes.

- I am aware that my anonymized data may be used in any papers, presentations, or publications that result from this research.

- I am aware that my anonymized data may be shared in a public online repository (e.g., Hugging Face), as described in the information letter.

- I am aware that my anonymized study data may be used for future research purposes, as described in the information letter.

- By providing your consent, you are not waiving your legal rights or releasing the investigator(s) or involved institution(s) from their legal and professional responsibilities.
`}
              />
        </div>
        <div className="button-container">
          <button 
            onClick={handleAcceptClick} 
            className="accept-button bg-primary-100"
            style={{fontSize: '25px'}}
          >
            I agree to participate
          </button>
        </div>
      </div>
      <style jsx>{`
        .modal {
          position: fixed;
          border: #E0E0E0;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 50;
          padding: 16px;
          box-sizing: border-box;
        }
        .modal-content {
          background: white;
          padding: 20px;
          border-radius: 8px;
          text-align: left;
          max-width: 600px;
          width: 100%;
          box-sizing: border-box;
          max-height: 90vh;
          display: flex;
          flex-direction: column;
        }
        .modal-title {
          display: block;
          text-align: center;
          margin-bottom: 10px;
          flex-shrink: 0;
        }
        .modal-body {
          text-align: left;
          overflow-y: auto;
          flex: 1;
          padding-right: 10px;
          margin: 10px 0;
          min-height: 0;
        }
        .button-container {
          text-align: center;
          padding-top: 16px;
          flex-shrink: 0;
          background: white;
          position: sticky;
          bottom: 0;
        }
        .accept-button {
          color: #4A4A4A;
          border: none;
          padding: 10px 20px;
          border-radius: 5px;
          cursor: pointer;
          transition: background-color 0.3s, color 0.3s;
        }
        .accept-button:hover {
          background-color: #424242;
          color: white;
        }

        @media (max-width: 640px) {
          .modal {
            padding: 12px;
            align-items: flex-start;
          }
          .modal-content {
            max-height: 95vh;
            margin-top: 16px;
            padding: 16px;
          }
          .modal-title {
            font-size: 20px !important;
          }
          .modal-body {
            padding-bottom: 8px;
          }
          .button-container {
            padding-top: 8px;
            margin-top: auto;
          }
          .accept-button {
            width: 100%;
            padding: 12px;
            font-size: 18px !important;
          }
        }
      `}</style>
    </div>
  );
}; 
