'use client';

import React, { useEffect, useState } from 'react';
import { Markdown } from '@/components/Shared';
import { hasAcceptedUserAgreement, acceptUserAgreement } from '@/pages_old/cookies';
import { setLocalStorage, setCookie } from '@/pages_old/cookies';
import { v4 as uuidv4 } from 'uuid';
import { useCohereClient } from '@/cohere-client';

interface UserAgreementModalProps {
  onAccept?: () => void;
}

export const TermsModal: React.FC<{ onAccept: () => void }> = ({ onAccept }) => {
  const [showTerms, setShowTerms] = useState(false);

  useEffect(() => {
    const hasAccepted = hasAcceptedUserAgreement();
    if (!hasAccepted) {
      setShowTerms(true);
    }
  }, []);

  const client = useCohereClient();

  const handleAcceptClick = () => {
    if (window.confirm('By clicking OK, I confirm that I am 18+ and agree that my data may be published or shared.')) {
      onAccept();
      acceptUserAgreement();
        client.createUser({
          email: "null",
          fullname: "null",
          headers: client.getHeaders()
        }).catch(error => {
          console.error('Failed to create user:', error);
        });
    }
  };

  if (!showTerms) return null;

  return (
    <div className="modal bg-marble-100">
      <div className="modal-content rounded-lg border border-marble-400">
        <span className="modal-title" style={{ fontFamily: 'Cambria', fontSize: '25px', fontWeight: 'bold' }}>
          Chat Annotator User Agreement
        </span>
        <hr style={{ paddingTop: '0.5rem', paddingBottom: '0.2rem'}}/>
        <div className="modal-body scrollable">
              <Markdown 
                style={{ fontSize: '15px' }} 
                text={`By using our app, which is powered by Cohere's API, you acknowledge and agree to the following terms regarding the data you provide:\n\n\u200B\n\n1. **Eligibility:** You must be **at least 18 years old** to use this app. By continuing to use the app, you confirm that you meet this age requirement.\n\n2. **Collection:** We may collect information, including the inputs you type into our app, the outputs generated by Cohere's API, and certain technical details about your device and connection (such as browser type, operating system, and IP address) provided by your device's request headers.\n\n3. **Use:** We may use the collected data for research purposes, to improve our services, and to develop new products or services, including commercial applications, and for security purposes, such as protecting against unauthorized access and attacks.\n\n4. **Sharing and Publication:** Your data, including the technical details collected from your device's request headers, may be published, shared with third parties, or used for analysis and reporting purposes.\n\n5. **Data Retention:** We may retain your data, including the technical details collected from your device's request headers, for as long as necessary.\n\n\u200B\n\nBy continuing to use our app, you provide your **explicit consent** to the collection, use, and potential sharing of your data as described above. If you **do not agree** with our data collection, use, and sharing practices, or if you **are under 18 years old**, please **do not use our app**.`}
              />
        </div>
        <div className="button-container">
          <button 
            onClick={handleAcceptClick} 
            className="accept-button bg-primary-100"
            style={{fontSize: '25px'}}
          >
            Accept
          </button>
        </div>
      </div>
      <style jsx>{`
        .modal {
          position: fixed;
          border: #E0E0E0;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 50;
          padding: 16px;
          box-sizing: border-box;
        }
        .modal-content {
          background: white;
          padding: 20px;
          border-radius: 8px;
          text-align: left;
          max-width: 600px;
          width: 100%;
          box-sizing: border-box;
          max-height: 90vh;
          display: flex;
          flex-direction: column;
        }
        .modal-title {
          display: block;
          text-align: center;
          margin-bottom: 10px;
          flex-shrink: 0;
        }
        .modal-body {
          text-align: left;
          overflow-y: auto;
          flex: 1;
          padding-right: 10px;
          margin: 10px 0;
          min-height: 0;
        }
        .button-container {
          text-align: center;
          padding-top: 16px;
          flex-shrink: 0;
          background: white;
          position: sticky;
          bottom: 0;
        }
        .accept-button {
          color: #4A4A4A;
          border: none;
          padding: 10px 20px;
          border-radius: 5px;
          cursor: pointer;
          transition: background-color 0.3s, color 0.3s;
        }
        .accept-button:hover {
          background-color: #424242;
          color: white;
        }

        @media (max-width: 640px) {
          .modal {
            padding: 12px;
            align-items: flex-start;
          }
          .modal-content {
            max-height: 95vh;
            margin-top: 16px;
            padding: 16px;
          }
          .modal-title {
            font-size: 20px !important;
          }
          .modal-body {
            padding-bottom: 8px;
          }
          .button-container {
            padding-top: 8px;
            margin-top: auto;
          }
          .accept-button {
            width: 100%;
            padding: 12px;
            font-size: 18px !important;
          }
        }
      `}</style>
    </div>
  );
}; 
